import type { Fixture } from '../../src/types/fixture';

export const FALLBACK_WEEK_1_MATCHES: Fixture[] = [
  {
    id: 'm1',
    week: 1,
    date: '2026-08-07',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 8604, name: 'BOLUSPOR', logo: 'https://file.mackolikfeeds.com/teams/8604?w=s' },
    awayTeam: { id: 34120, name: 'MANİSA FK', logo: 'https://file.mackolikfeeds.com/teams/34120?w=s' },
    homeScore: 1,
    awayScore: 2,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 2,
  },
  {
    id: 'm2',
    week: 1,
    date: '2026-08-08',
    time: '14:00',
    status: 'played',
    homeTeam: { id: 11986, name: 'BANDIRMASPOR', logo: 'https://file.mackolikfeeds.com/teams/11986?w=s' },
    awayTeam: { id: 2226, name: 'İSTANBULSPOR', logo: 'https://file.mackolikfeeds.com/teams/2226?w=s' },
    homeScore: 3,
    awayScore: 0,
    halfTimeHomeScore: 2,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm3',
    week: 1,
    date: '2026-08-08',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 19664, name: 'ÜMRANİYESPOR', logo: 'https://file.mackolikfeeds.com/teams/19664?w=s' },
    awayTeam: { id: 44751, name: 'MARDİN 1969 SPOR', logo: 'https://file.mackolikfeeds.com/teams/44751?w=s' },
    homeScore: 0,
    awayScore: 0,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm4',
    week: 1,
    date: '2026-08-08',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 2238, name: 'SİVASSPOR', logo: 'https://file.mackolikfeeds.com/teams/2238?w=s' },
    awayTeam: { id: 39486, name: 'ESENLER EROKSPOR', logo: 'https://file.mackolikfeeds.com/teams/39486?w=s' },
    homeScore: 0,
    awayScore: 0,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm5',
    week: 1,
    date: '2026-08-08',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 2236, name: 'ANTALYASPOR', logo: 'https://file.mackolikfeeds.com/teams/2236?w=s' },
    awayTeam: { id: 7284, name: 'KEÇİÖRENGÜCÜ', logo: 'https://file.mackolikfeeds.com/teams/7284?w=s' },
    homeScore: 4,
    awayScore: 3,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm6',
    week: 1,
    date: '2026-08-09',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 54027, name: 'IĞDIR FK', logo: 'https://file.mackolikfeeds.com/teams/54027?w=s' },
    awayTeam: { id: 3014, name: 'F. KARAGÜMRÜK', logo: 'https://file.mackolikfeeds.com/teams/3014?w=s' },
    homeScore: 2,
    awayScore: 0,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm7',
    week: 1,
    date: '2026-08-09',
    time: '16:00',
    status: 'played',
    homeTeam: { id: 2344, name: 'SARIYER', logo: 'https://file.mackolikfeeds.com/teams/2344?w=s' },
    awayTeam: { id: 14051, name: 'MUĞLASPOR', logo: 'https://file.mackolikfeeds.com/teams/14051?w=s' },
    homeScore: 2,
    awayScore: 0,
    halfTimeHomeScore: 1,
    halfTimeAwayScore: 0,
  },
  {
    id: 'm8',
    week: 1,
    date: '2026-08-09',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 2346, name: 'VANSPOR FK', logo: 'https://file.mackolikfeeds.com/teams/2346?w=s' },
    awayTeam: { id: 2235, name: 'KAYSERİSPOR', logo: 'https://file.mackolikfeeds.com/teams/2235?w=s' },
    homeScore: 0,
    awayScore: 2,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 1,
  },
  {
    id: 'm9',
    week: 1,
    date: '2026-08-09',
    time: '18:30',
    status: 'played',
    homeTeam: { id: 34119, name: 'BODRUM FK', logo: 'https://file.mackolikfeeds.com/teams/34119?w=s' },
    awayTeam: { id: 2227, name: 'BURSASPOR', logo: 'https://file.mackolikfeeds.com/teams/2227?w=s' },
    homeScore: 0,
    awayScore: 2,
    halfTimeHomeScore: 0,
    halfTimeAwayScore: 2,
  },
  {
    id: 'm10',
    week: 1,
    date: '2026-08-10',
    time: '18:30',
    status: 'fixture',
    homeTeam: { id: 9153, name: 'PENDİKSPOR', logo: 'https://file.mackolikfeeds.com/teams/9153?w=s' },
    awayTeam: { id: 2887, name: 'BATMAN PETROLSPOR', logo: 'https://file.mackolikfeeds.com/teams/2887?w=s' },
    homeScore: null,
    awayScore: null,
    halfTimeHomeScore: null,
    halfTimeAwayScore: null,
  },
];
